on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Just a job for testing
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Annotation
        uses: ./
        id: annotation
        with:
          applicationId: ${{ secrets.APPLICATION_ID }}
          apiKey: ${{secrets.API_KEY}}
          releaseName: ${{ github.event_name }}
          message: ${{ github.ref }}
          actor: ${{ github.actor }}

      - name: Get the output time
        run: echo "The time was ${{ steps.annotation.outputs.time }}"
